# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-14 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='St_face',
            fields=[
                ('face', models.TextField(primary_key=True, serialize=False)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'St_face',
            },
        ),
        migrations.CreateModel(
            name='Travel_history',
            fields=[
                ('student_id', models.TextField(primary_key=True, serialize=False)),
                ('history_3m', models.TextField()),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Travel_history',
            },
        ),
        migrations.AddField(
            model_name='st_face',
            name='student_who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swho', to='face.Travel_history'),
        ),
    ]
